config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'visited', to: 'static_pages#visited'

  resources :trips do
    resources :locations
    resources :pack_items
  end
  resources :locations do
  	resources :addresses
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :location
	validates_presence_of :street, :city, :country, :zip

	def self.states
		%w(--- AK AL AR AZ CA CO CT DC DE FL GA HI IA ID IL IN KS KY LA MA MD ME MI MN MO MS MT NC ND NE NH NJ NM NV NY OH OK OR PA RI SC SD TN TX UT VA VT WA WI WV WY)
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
	belongs_to :trip
	has_one :address, dependent: :destroy

	has_attached_file :image, styles: { small: ["300x300#", :jpg] }
	validates_attachment :image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

	validates_presence_of :where

	def self.is_like_options
		%w(None Beach Day\ Hike Camp\ Out Snowy Rural Metro Formal Boat)
	end

end

app/models/pack_item.rb
class PackItem < ApplicationRecord
	belongs_to :trip

	validates_presence_of :name, :location

	def self.mark_packed(item)
		item[:packed] = true
		item
	end

	def self.loc_options(trip)
		options = ['General']
		trip.locations.each do |location|
			options	<< location.where.to_s
		end
		options
	end

	def self.by_is_like(trip)
		options = []
		trip.locations.each do |location|
			options << location.is_like.to_s
		end
		options.uniq
	end


	def self.filter_items(location)
		where(location: location).where(packed: false)
	end

	def self.filter_packed_items(location)
		where(location: location).where(packed: true)
	end

	def self.pack_recs
		{beach: ['sunscreen', 'towel'], formal: ['tie', 'dress shoes'], dayhike: ['water bottle', 'hiking shoes'], metro: ['walking shoes', 'transportation plans', 'pepper spray'], snowy: ['gloves', 'scarf', 'wool socks'] }
	end
end

app/models/trip.rb
class Trip < ApplicationRecord
	has_many :locations, dependent: :destroy
	has_many :pack_items, dependent: :destroy

	validates_presence_of :name

	has_attached_file :image, styles: { small: ["300x300#", :jpg] }
	validates_attachment :image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
	
	def self.by_date
		order(:begin)
	end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  # before_action :trip
  before_action :location
  before_action :address, only: [:show, :edit, :update, :destroy]

  def index
    @address = @location.address
  end


  def show
  end

  def new
    @address = Address.new
  end


  def create
    @address = Address.new(address_params)
    if @address.save
      redirect_to location_address_path(@location, @address)
    else
      render :new
    end
  end

  def edit
  end


  def update
    if @address.update(address_params)
      redirect_to location_address_path(@location, @address)
    else
      render :edit
    end
  end


  def destroy
    @address.destroy
    redirect_to location_address_path(@location, @address)
  end



  private

  def address
    @address = @location.address
  end

  def location
    @location = Location.find(params[:location_id])
  end

  # def trip
  #   @trip = Trip.find(params[:trip_id])
  # end

  def address_params
    params.require(:address).permit(:street, :city, :state, :country, :zip, :location_id)
  end








end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
  	@trip = Trip.find(params[:trip_id])
  	@locations = @trip.locations
   end

  def show
  	@trip = Trip.find(params[:trip_id])
  	@location = @trip.locations.find(params[:id])
  end

  def new
  	@trip = Trip.find(params[:trip_id])
    @location = @trip.locations.new
  end

  def create
  	@trip = Trip.find(params[:trip_id])
  	@location = @trip.locations.new(location_params)
    if @location.save
  	  redirect_to trip_locations_path(@trip)
    else
	  render :new
    end
  end

  def edit
  	@trip = Trip.find(params[:trip_id])
  	@location = @trip.locations.find(params[:id])
  end

  def update
  	@trip = Trip.find(params[:trip_id])
  	@location = @trip.locations.find(params[:id])
  	if @location.update(location_params)
  	  redirect_to trip_locations_path(@trip)
  	else
      render :edit
    end
  end

  def destroy
  	@trip = Trip.find(params[:trip_id])
  	@location = @trip.locations.find(params[:id]).destroy
  	redirect_to trip_locations_path(@trip)
  end

  private

  	def location_params
  	  params.require(:location).permit(:where, :is_like, :days, :notes, :image)
	end

	def trip
		@trip = Trip.find(params[trip_id])
	end

	def location
		@location = @trip.locations.find(params[:id])
	end
end

app/controllers/pack_items_controller.rb
class PackItemsController < ApplicationController
  def index
  	@trip = Trip.find(params[:trip_id])
  	@locations = PackItem.loc_options(@trip)
  	@pack_items = @trip.pack_items
  end

  def new
  	@trip = Trip.find(params[:trip_id])
  	@pack_item = PackItem.new
  end

  def create
  	@trip = Trip.find(params[:trip_id])
  	@pack_item = @trip.pack_items.new(pack_item_params)

  	if @pack_item.save
  	  redirect_to trip_pack_items_path(@trip)
	else
	  render :new
	end
  end

  def show
  	@trip = Trip.find(params[:trip_id])
  	@locations = @trip.locations
  	@pack_item = @trip.pack_items.find(params[:id])
  end

  def edit
  	@trip = Trip.find(params[:trip_id])
  	@pack_item = @trip.pack_items.find(params[:id])
  end

  def update
  	@trip = Trip.find(params[:trip_id])
  	@pack_item = @trip.pack_items.find(params[:id])

  	if @pack_item.update(pack_item_params)
  	  redirect_to trip_pack_items_path(@trip)
    else
      render :edit
    end
  end

  def destroy
  	@trip = Trip.find(params[:trip_id])
  	@pack_item = @trip.pack_items.find(params[:id]).destroy
	redirect_to trip_pack_items_path(@trip)
  end

  private

  def pack_item_params
  	params.require(:pack_item).permit(:name, :is_like, :location, :notes, :packed)
  end

  def trip
  	@trip = Trip.find(params[:trip_id])
  end

  def pack_items
  	@pack_item = @trip.pack_item(params[:id])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'static_pages'

  def home
  end

  def visited
  	@locations = Location.all
  end


end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :trip, only: [:edit, :update, :destroy, :show]

  def index
    @trips = Trip.all
  end

  def show
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    if @trip.save
      redirect_to trip_locations_path(@trip)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @trip.update(trip_params)
      redirect_to trip_locations_path(@trip)
    else
      render :edit
    end
  end

  def destroy
    @trip.destroy
    redirect_to trips_path
  end

  private

    def trip_params
      params.require(:trip).permit(:name, :begin, :end, :people, :notes, :image)
    end

    def trip
      @trip = Trip.find(params[:id])
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pack_items_helper.rb
module PackItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/addresses/_form.html.erb
<h1> Address for <%= @location.where %> </h1>

<% if @address.errors.any? %>
	<ul>
		<% @address.errors.full_messages.each do |error| %>
		<li> <%= error %> </li>
	<% end %>
	</ul>
<% end %>

<%= form_for [@trip, @location, @address] do |f| %>
  <%= f.label :street %>
  <%= f.text_field :street, placeholder: '123 Street' %>
<br />

  <%= f.label :city %>
  <%= f.text_field :city %>
<br />

	<%= f.label :state %>
	<%= f.select :state, Address.states %>

<br />

  <%= f.label :country%>
  <%= f.text_field :country%>
<br />

  <%= f.label :zip %>
  <%= f.number_field :zip %>
<br />

  <%= f.hidden_field :location_id, :value => @location.id %>

  <%= f.submit 'Submit', class: 'btn'%>

<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render(partial: 'form') %>

app/views/addresses/index.html.erb
<h1><%= @location.where %> Address</h1>

<% if @address.any? %>
  <ul>
    <% @address.each do |address| %>
      <li class='address-info-text'> <%= address.info %> - <%=
        link_to 'Show', trip_location_address_path(@trip, @location, address) %> </li>
      <% end %>
  </ul>
<% else %>
  <h3>No Addresses have been created. Clink the link below to create one.</h3>
<% end %>

<%= link_to 'New Address', new_trip_location_address_path(@trip, @location) %>

app/views/addresses/new.html.erb
<h1>Add Address</h1>

<%= render(partial: 'form') %>

app/views/addresses/show.html.erb
<h1>Address for <%= @location.where %></h1>
<br />
<p>Street: <%= @address.street %></p>
<br />
<p>City: <%= @address.city%></p>
<br />
<p>State <%= @address.state%></p>
<br />
<p>Country: <%= @address.country%></p>
<br />
<p>Zipcode: <%= @address.zip%></p>

<%= link_to 'Back to Location', trip_location_path(@location.trip_id, @location) %>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12 grey-text text-darken-4">
        <h5>Trip Tracker</h5>
        <p>Upload your trip photos, keep track of
                            favorite locations and addresses, and revisit the fun.</p>
      </div>
      <div class="col l4 offset-l2 s12 grey-text text-darken-4">
        <h5>menu</h5>
        <ul>
          <li><%=link_to 'My Trips', trips_path%></li>
          <li><%=link_to "I've Visited", visited_path%></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container grey-text text-darken-4">
    © 2016 Trippin Trip tracking
    <%=link_to 'Home', root_path, class: 'right'%>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="z-depth-0">
  <div class="nav-wrapper">
    <a href="/" class="brand-logo">TRIPPIN</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%=link_to 'Home', root_path %></li>
      <li><%=link_to 'My Trips', trips_path %></li>
      <li><%=link_to "I've Visited", visited_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Triptracker</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Maven+Pro:400,900|Pacifico|Poiret+One" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
    </div>
    <hr />
    <div class="container">
    <%= yield %>


    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Triptracker</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Maven+Pro:400,900|Pacifico|Poiret+One" rel="stylesheet">
  </head>

  <body class="static-bg-img">
    <div class="container row">
      <div class="col s12 m3 pull-left"><h1>TRIPPIN</h1></div>
      <div class="col s12 m7 pull-left"><p>trip tracking</p></div>
    </div>
    <div class="clear">
    <%= yield %>
    </div>
    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<% if @location.errors.any? %>
	<ul>
		<% @location.errors.full_messages.each do |error| %>
		<li> <%= error %> </li>
	<% end %>
	</ul>
<% end %>

<div class='row'>
	<%= form_for [@trip, @location] do |f| %>
		<div class='row'>
			<%= f.label :where %>
			<%= f.text_field :where, require: true %>
		</div>
		<div class='row'>
			<%= f.label :is_like, class: 'active' %>
			<%= f.select :is_like, Location.is_like_options, {include_blank: 'What is the location like?'} %>
		</div>
		<div class='row'>
			<%= f.label :days, class: 'active' %>
			<%= f.number_field :days %>
		</div>
		<div class='row'>
			<%= f.label :notes %>
			<%= f.text_area :notes, class: "materialize-textarea" %>
		</div>
		<div class='row'>
			<%= f.label :image, class: 'active', class: 'btn' %>
			<span style='display:none'> <%= f.file_field :image, class: 'btn' %> </span>
		</div>
		<div class='row'>
			<%= f.submit 'Submit', class: 'btn' %>
		</div>
	<% end %>
</div>

<script async>
	$(document).ready(function() {
  		$('select').material_select();
	});
</script>

app/views/locations/edit.html.erb
<h2>Update <%= @location.where %> </h2>

<%= render(partial: 'form') %>

app/views/locations/index.html.erb
<h2> <%= @trip.name %> Destinations</h2>

<div class='col s12'>
	<%= "Trip Dates: #{@trip.begin} - #{@trip.end} |" if @trip.begin && @trip.end %>
	<%= "With: #{@trip.people} |" if @trip.people %> <br>
	<%= "Notes: #{@trip.notes} |" if @trip.notes %>
	<%= link_to 'Edit Trip Details', edit_trip_path(@trip) %> |
	<%= link_to 'View Packing List', trip_pack_items_path(@trip) %> |
	<%= link_to 'Add New Location', new_trip_location_path(@trip) %> <br><br>
</div>


<% if @locations.empty? %>
	<p> You haven't added any locations to this trip. </p>
<% else %>

	<ul>
		<% @locations.each do |location| %>
			<div class='row'>
				<div class='col s6'>
					<li>
						<h4> <%= link_to location.where, trip_location_path(@trip, location) %> </h4> <br>
						<%= location.notes == "" ? nil : "Notes: #{location.notes}" %>
						<%= location.address ? (button_to 'Edit Address', edit_location_address_path(location, location.address), method: :get, class: 'btn') : (button_to 'Add Address', new_location_address_path(location), method: :get, class: 'btn') %> <br>
						<%= button_to 'Delete Location', trip_location_path(@trip, location), method: :delete, data: {confirm: 'You will lose all data about this location. Are you sure you want to delete?'}, class: 'btn' %>
					</li>
				</div>
				<div class='col s6'>
					<%= location.image? ? image_tag(location.image.url(:small)) : nil %>
				</div>
			</div>
		<% end %>
	</ul>
<% end %>

app/views/locations/new.html.erb
<h2> New Location</h2>

<%= render(partial: 'form') %>

app/views/locations/show.html.erb
<h2> <%= @location.where %> Details</h2>

<p> Destination Type: <%= @location.is_like %> </p>
<p> Days at Location: <%= @location.days %> </p>
<p> Notes: <%= @location.notes %> </p>

<%= image_tag(@location.image.url) %>

<div class='row'>
	<div class='col s12 m4'>
	<%= button_to 'Edit Location Details', edit_trip_location_path(@trip, @location), method: :get, class: 'btn' %> 
	</div>
	<div class='col s12 m4'>
	<%= @location.address ? (button_to 'Edit Address', edit_location_address_path(@location, @location.address), method: :get, class: 'btn') : (button_to 'Add Address', new_location_address_path(@location), method: :get, class: 'btn') %>
	</div>
	<div class='col s12 m4'>
	<%= button_to 'Delete Location', trip_location_path(@trip, @location), method: :delete, data: {confirm: 'You will lose all data about this location. Are you sure you want to delete?'}, class: 'btn' %>
	</div>
</div>

app/views/pack_items/_form.html.erb
<% if @pack_item.errors.any? %>
	<ul>
		<% @pack_item.errors.full_messages.each do |error| %>
		<li> <%= error %> </li>
	<% end %>
	</ul>
<% end %>

<div class='row'>
	<%= form_for [@trip, @pack_item]  do |f| %>
	<div class='row'>
			<%= f.label :name %>
			<%= f.text_field :name, require: true %>
	</div>
	<div class='row'>
			<%= f.label :location %>
			<%= f.select :location, PackItem.loc_options(@trip), {include_blank: 'Which location is this for?'} %>
	</div>	
	<div class='row'>
			<%= f.label :notes %>
			<%= f.text_area :notes, class: 'materialize-textarea' %>
	</div>
	<div class='row'>

			<%= f.check_box :packed %>
			<%= f.label :packed %>
	</div>
	<div class='row'>
			<%= f.submit 'Submit', class: 'btn' %>
	</div>
	<% end %>
</div>

<script async>
	$(document).ready(function() {
  		$('select').material_select();
	});
</script>

app/views/pack_items/edit.html.erb
<h2>Edit <%= @pack_item.name %> for <%= @trip.name %> Packing List</h2>

<%= render(partial: 'form') %>

app/views/pack_items/index.html.erb
<h2>Packing List for <%= @trip.name %> </h2>

<%= link_to 'Add New Item', new_trip_pack_item_path(@trip) %> |
<%= link_to 'Location View', trip_locations_path(@trip) %>

<div class='row'>
	<div class='col s12 m6'>
		<h4>Still to Pack</h4>
		<ul>
			<% @locations.each do |location| %>
			<li> <h5> <%= location %> </h5>
				<ul>
					<% PackItem.filter_items(location).each do |item| %>
					<li> 
						<%= link_to item.name, edit_trip_pack_item_path(@trip, item) %> - <%= item.notes %>
						<%= link_to 'Delete Item', trip_pack_item_path(@trip, item), method: :delete %>
					</li>
					<% end %>
				</ul>
			</li>
			<% end %>
		</ul>
	</div>

	<div class='col s12 m6'>
		<h4>Packed!</h4>
		<ul>
			<% @locations.each do |location| %>
			<li> <h5> <%= location %> </h5>
				<ul>
					<% PackItem.filter_packed_items(location).each do |item| %>
					<li> 
						<%= link_to item.name, edit_trip_pack_item_path(@trip, item) %> - <%= item.notes %>
						<%= link_to 'Delete Item', trip_pack_item_path(@trip, item), method: :delete %>
						 
					</li>
					<% end %>
				</ul>
			</li>
			<% end %>
		</ul>
	</div>
</div>

<div class='row'>
	<h4>Recommended</h4>
	<ul>
		<% PackItem.by_is_like(@trip).each do |type| %>
			<li> 
				<h5> <%= type %> </h5>
				<ul>
				<% PackItem.pack_recs[type.downcase.gsub(/\s+/, "").to_sym].each do |item| %>
					<li> <%= item %> </li>
				<% end %>
				</ul>
			</li>
		<% end %>
	</ul>
</div>

app/views/pack_items/new.html.erb
<h2>New Item for <%= @trip.name %> Packing List</h2>

<%= render(partial: 'form') %>

app/views/pack_items/show.html.erb
<h1>PackItems#show</h1>
<p>Find me in app/views/pack_items/show.html.erb</p>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="col s12 center-align">
    <div class="waves-effect waves-light btn enter-btn"><%= link_to 'ENTER', trips_path %></div>
  </div>
</div>

app/views/static_pages/visited.html.erb
<h1> Places I've visited </h1>

<section>
<br><br>
	<% if @locations.empty? %>
		<p> You haven't planned any locations for your trips yet! </p>
	<% else %>
	<div class='row'>
			<% @locations.each do |location| %>
				<% if location.image? %>
					<div class='col s12 m4'>
						<h5 class='visited'> 
							<%= link_to location.where, trip_location_path(location[:trip_id], location) %> <br>
							<%= image_tag(location.image.url(:small)) %>
						</h5>
					</div>
				<% end %>
			<% end %>
	</div>
	<% end %>
</section>

app/views/trips/_form.html.erb
  <% if @trip.errors.any? %>
  	<ul>
  		<% @trip.errors.full_messages.each do |error| %>
  		<li> <%= error %> </li>
  	<% end %>
  	</ul>
  <% end %>
<div class="row">
  <div class="col s12 m8 offset-m2">
    <%= form_for @trip do |f| %>
    <div class="input-field s12">
      <%= f.label :name, 'Trip Name', class: 'active'%>
      <%= f.text_field :name, required: true %>
    </div>

  <div class="row">
    <div class="input-field col s6 m6">
      <%= f.label :begin, 'Begin Trip', class: 'active' %>
      <%= f.date_field :begin, placeholder: "start date" %>
    </div>

    <div class="input-field col s6 m6">
      <%= f.label :end, 'End Trip', class: 'active' %>
      <%= f.date_field :end %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s6 m6">
      <%= f.label :people, class: 'active' %>
      <%= f.text_area :people, placeholder: "Who's coming with you?", class: 'materialize-textarea'%>
    </div>

    <div class="input-field col s6 m6">
      <i class="material-icons">add_a_photo</i>
      <% f.label :image%>
      <%= f.file_field :image%>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12 m8">
      <%= f.submit 'submit', class: 'btn'%>
    </div>
  </div>
  <%end%>

  </div>
</div>

app/views/trips/_sidenav.html.erb
<%=link_to 'add location', trips_path %> 
<%=link_to "I've Visited", visited_path %>

app/views/trips/edit.html.erb
<div class="row">
  <div class="col s12">
    <h4 class="right-align"> Edit Trip Info: <%= @trip.name %> </h4>
  </div>
  <div class="col s12 right-align"> 
    <i class="material-icons">delete_forever</i><%= link_to 'Delete', trip_path(@trip),
    method: :delete, data: {confirm: 'You will lose everything in this trip, are you sure you want to delete?'} %>
  </div>
  <%= render(partial:'form') %>

  <%=link_to 'BACK', trips_path %>

</div>

app/views/trips/index.html.erb
<div class="row">

    <% if @trips.any? %>
    <div class="col s12">
      <i class="tiny material-icons">add_box</i><%= link_to 'Add A Trip', new_trip_path %>
    </div>

    
      <% @trips.each do |trip| %>
      <div class="col s12 m4">
<!--       <div class="pull-left"> -->
        <h4><%= link_to trip.name, trip_locations_path(trip) %></h4>
          <%= image_tag(trip.image.url(:small))%>
<!--       </div> -->
    </div>
      <% end %>

    <% else %>
      <div class="col s12 search-trip center-align">
          <h4>You haven't tripped yet! Get at it.</h4>
          <p>Start <a class="white-text" href="http://www.google.com" target="_blank">Googling</a> where to go or</p>

      <div class="waves-effect waves-light btn enter-btn"><%= link_to 'ADD TRIP', new_trip_path %></div>
      </div>
    <% end %>

  </div>

app/views/trips/new.html.erb
<div class="row">
  <div class="col s12">
    <h4 class="right-align"> Add A Trip </h4>
  </div>

  <%= render(partial:'form') %>
  <p class="lead col s12"><%=link_to 'BACK', trips_path %></p>
</div>

app/views/trips/show.html.erb
<div>
  <h2><%= @trip.name %></h2>
  <p>I guess you've been trippin, because you are ready to tell use about it now.</p>
  <%= link_to 'Start Adding Your Trip Info', new_trip_location_path(@trip) %>